apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infer-models-pv-claim
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: infer-models-pv
  storageClassName: ""