apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-frontend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-frontend
  template:
    metadata:
      labels:
        app: astro-frontend
    spec:
      containers:
      - name: astro
        image: goncammej/vividus_front:0.0.1
        ports:
        - containerPort: 4321
        envFrom:
            - configMapRef:
                name: frontend-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: astro-frontend-service
  namespace: app
spec:
  selector:
    app: astro-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4321