apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-pv-claim
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: datasets-pv
  storageClassName: ""