apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmp-inference-pv
  labels:
    type: tmp-inference
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp_inference
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""