apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmp-inference-pv-claim
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: tmp-inference-pv 
  storageClassName: ""